name: zacrac
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # A Flutter package to use fonts from fonts.google.com. Supports HTTP fetching, caching, and asset bundling.
  google_fonts: ^4.0.3
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.5.4
  # Flutter Page Transition Package which is the transition second page
  page_transition: ^2.0.9
  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^1.1.5
  # A light weight package for flutter apps, that easily shows a splash screen with a nice fade animation.
  animated_splash_screen: ^1.3.0
  # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_core: ^2.7.0
  # Library that allows you to display progress widgets based on percentage, can be Circular or Linear, you can also customize it to your needs.
  percent_indicator: ^4.2.3
  # Annotations for the freezed code-generator. This package does nothing without freezed too. 
  freezed_annotation: ^2.2.0
  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.8.0
  # Chopper is an http client generator using source_gen, inspired by Retrofit
  chopper: ^6.1.1
  # Provides APIs for debugging and error logging, similar to loggers in other languages, such as the Closure JS Logger and java.util.logging.Logger.
  logging: ^1.1.1
  # Functional Programming in Dart. Purify your Dart code using efficient immutable data structures, monads, lenses and other FP tools.
  dartz: ^0.10.1
  # for circular progresss bar
  dashed_circular_progress_bar: ^0.0.4
  # for smooth page trnsition
  smooth_page_indicator: ^1.1.0

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps, packages, and plugins to encourage good coding practices.
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

    

  